
networks:
  service:
    name: rechnungsverwaltung-service-main
  architecture:
    name: main

services:
  ## Router
  router-01-rechnungsverwaltung:
    networks:
      - service
    build: ./db_config_router
    container_name: router-01-rechnungsverwaltung
    command: mongos --port 27017 --configdb rechnungsverwaltung-mongodb-config-server/db-rechnung-config1:27017,db-rechnung-config2:27017,db-rechnung-config3:27017 --bind_ip_all
    ports:
      - 27117:27017

  router-02-rechnungsverwaltung:
    networks:
      - service
    build: ./db_config_router
    container_name: router-02-rechnungsverwaltung
    command: mongos --port 27017 --configdb rechnungsverwaltung-mongodb-config-server/db-rechnung-config1:27017,db-rechnung-config2:27017,db-rechnung-config3:27017 --bind_ip_all
    ports:
      - 27118:27017

  ## Config Servers
  db-rechnung-config1:
    networks:
      - service
    build: ./db_config_router
    ports:
      - 27017:27017
    container_name: db-rechnung-config1
    command: mongod --port 27017 --configsvr --replSet rechnungsverwaltung-mongodb-config-server

  db-rechnung-config2:
    networks:
      - service
    build: ./db_config_router
    ports:
      - 27018:27017
    container_name: db-rechnung-config2
    command: mongod --port 27017 --configsvr --replSet rechnungsverwaltung-mongodb-config-server

  db-rechnung-config3:
    networks:
      - service
    build: ./db_config_router
    ports:
      - 27019:27017
    container_name: db-rechnung-config3
    command: mongod --port 27017 --configsvr --replSet rechnungsverwaltung-mongodb-config-server

  ## Shards 1
  shard-01-rechnungsverwaltung1:
    networks:
      - service
    build: ./db_shard
    container_name: shard-01-rechnungsverwaltung1
    command: mongod --port 27017 --shardsvr --replSet shard-01-db-rechnungsverwaltung
    ports:
      - 27122:27017

  shard-01-rechnungsverwaltung2:
    networks:
      - service
    build: ./db_shard
    container_name: shard-01-rechnungsverwaltung2
    command: mongod --port 27017 --shardsvr --replSet shard-01-db-rechnungsverwaltung
    ports:
      - 27123:27017

  shard-01-rechnungsverwaltung3:
    networks:
      - service
    build: ./db_shard
    container_name: shard01rechnungsverwaltung3
    command: mongod --port 27017 --shardsvr --replSet shard-01-db-rechnungsverwaltung
    ports:
      - 27124:27017


  ## Shards 2
  shard-02-rechnungsverwaltung1:
    networks:
      - service
    build: ./db_shard
    container_name: shard-02-rechnungsverwaltung1
    command: mongod --port 27017 --shardsvr --replSet shard-02-db-rechnungsverwaltung
    ports:
      - 27125:27017

  shard-02-rechnungsverwaltung2:
    networks:
      - service
    build: ./db_shard
    container_name: shard-02-rechnungsverwaltung2
    command: mongod --port 27017 --shardsvr --replSet shard-02-db-rechnungsverwaltung
    ports:
      - 27126:27017

  shard-02-rechnungsverwaltung3:
    networks:
      - service
    build: ./db_shard
    container_name: shard-02-rechnungsverwaltung3
    command: mongod --port 27017 --shardsvr --replSet shard-02-db-rechnungsverwaltung
    ports:
      - 27127:27017

  ## Rest API
  rest-api-rechnungsverwaltung1:
    networks:
      - service
      - architecture
    container_name: rest-api-rechnungsverwaltung1
    build: ./rest_api
    environment:
      - DBUSER=admin
      - DBPWD=test1234
      - MONGODBROUTER=mongodb://router-01-rechnungsverwaltung/backend
      - BENUTZERVERWALTUNG=rest-api-benutzerverwaltung1
      - BENUTZERVERWALTUNGPORT=8000
    ports:
      - 8001:8000
