
networks:
  main:

services:
  rest_api_rechnungsverwaltung:
    image: rest_api_rechnungsverwaltung_ms
    ports:
      - "8000:8000"
    networks:
      - main

  database_rechnungsverwaltung:
    image: datenbank_mongodb_rechnungsverwaltung_ms
    ports:
      - "27017:27017"
    networks:
      - main
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test1234